config/routes.rb
Rails.application.routes.draw do
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: "task"
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# tasks/:id
# tasks/:id/edit

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <p>Should display user tasks and completion status</p>
  <p>When you click each task should get tasks/:id</p>
  <p>Then from each task tasks/:id/edit</p>

  <ul>
    <li><% @tasks.each do |task| %>
      <%= link_to task.title, task_path(task) %>
    <% end %>
    </li>
  </ul>

  <%= link_to "Add a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%# Task Title %>
<%# Task Details %>
<%= form_for(@task) do |t| %>
  <div class="task-form">
    <h4>Title</h4>
    <%= t.text_field :title %>
  </div>

  <div class="task-form">
    <h4>Details</h4>
    <%= t.text_field :details %>
  </div>

<%# Submit Button %>
   <div class="task-form">
    <%= t.submit value: "Create Task"%>
  </div>
<% end %>


  <%# <%= t.check_box :status %>

app/views/tasks/show.html.erb
<p>displays individual task names and status</p>
<h1><%= @task.title %></h1>
<p><%=  %></p>